export const START_LOADING_HEADLINES = 'START_LOADING_HEADLINES';
export const END_LOADING_HEADLINES = 'END_LOADING_HEADLINES';
export const FETCH_HEADLINES = 'FETCH_HEADLINES';
export const ERROR_HEADLINES = 'ERROR_HEADLINES';

export const START_LOADING_SOURCES = 'START_LOADING_SOURCES';
export const END_LOADING_SOURCES = 'END_LOADING_SOURCES';
export const FETCH_SOURCES = 'FETCH_SOURCES';
export const ERROR_SOURCES = 'ERROR_SOURCES';
